#!/bin/sh

set -e


echo "running post install"

HOST_IP_LIST=`ifconfig | sed -n -e 's/:127\.0\.0\.1 //g' -e 's/ *inet addr:\([0-9.]\+\).*/\1/gp'`
HOST_IP=`echo $HOST_IP_LIST | cut -d',' -f1`
echo $HOST_IP
easy_install argparse
easy_install pycurl

if [-e /usr/bin/server-manager ]; then
	unlink /usr/bin/server-manager
fi

ln -s /opt/contrail/server_manager/client/server-manager /usr/bin/server-manager
