#!/bin/sh

set -e


echo "running post install"

#cp -r /etc/contrail/cobbler /etc/
cp -r /etc/contrail/puppet /etc/

cp /etc/contrail/cobbler/dhcp.template.u /etc/cobbler/dhcp.template
mkdir -p /var/www/html
mkdir -p /var/www/html/kickstarts
cp -r /etc/contrail/kickstarts /var/www/html/
mkdir -p /var/www/html/contrail

cp -u /etc/puppet/puppet_init_rd /var/www/cobbler/aux/puppet
easy_install argparse
easy_install paramiko
easy_install pycrypto

mkdir -p /etc/contrail/images/

sed -i 's/puppet_auto_setup: 0/puppet_auto_setup: 1/g' /etc/cobbler/settings
sed -i 's/sign_puppet_certs_automatically: 0/sign_puppet_certs_automatically: 1/g' /etc/cobbler/settings

sed -i 's/remove_old_puppet_certs_automatically: 0/remove_old_puppet_certs_automatically: 1/g' /etc/cobbler/settings
sed -i 's/manage_dhcp: 0/manage_dhcp: 1/g' /etc/cobbler/settings
sed -i 's/manage_dns: 0/manage_dns: 1/g' /etc/cobbler/settings
sed -i 's:DocumentRoot /var/www:DocumentRoot /var/www/html:g' /etc/apache2/sites-available/default

HOST_IP_LIST=`ifconfig | sed -n -e 's/:127\.0\.0\.1 //g' -e 's/ *inet addr:\([0-9.]\+\).*/\1/gp'`
HOST_IP=`echo $HOST_IP_LIST | cut -d',' -f1`
echo $HOST_IP

sed -i "s/10.84.51.11/$HOST_IP/" /etc/cobbler/settings
update-rc.d contrail_smgrd defaults
#/sbin/chkconfig --add contrail_smgrd
sed -i "s/authn_denyall/authn_testing/g" /etc/cobbler/modules.conf
sed -i "s/authn_configfile/authn_testing/g" /etc/cobbler/modules.conf

sed -i "s/127.0.0.1/$HOST_IP/g" /opt/contrail/server_manager/smgr_config.ini

service apache2 restart
service xinetd restart
service cobbler restart


service puppetmaster restart



#update-rc.d apache2 defaults
#update-rc.d xinetd defaults
#update-rc.d cobbler defaults
#update-rc.d puppetmaster defaults

#puppet master
service contrail_smgrd restart

