#! /bin/sh
#
# chkconfig: 2345 55 45
# description:	The server mangement daemon maintains all the servers belonging to contrail ecosystem.
# processname: contrail-server-manager
# config: /etc/sysconfig/contrail-server-manager
# pidfile: /var/run/contrail-server-manager/contrail-server-manager.pid

#SYSTEMCTL_SKIP_REDIRECT=1

# Source function library.
. /etc/init.d/functions


USER=root
RETVAL=0
prog="contrail-server-manager"
pidfile=${PIDFILE-/var/run/$prog/$prog.pid}

if [ -f /etc/sysconfig/$prog ];then 
	. /etc/sysconfig/$prog
fi



start () {
	echo -n $"Starting $prog: "
	# Ensure that $pidfile directory has proper permissions and exists
	piddir=`dirname $pidfile`
	if [ ! -d $piddir ]; then
		mkdir $piddir
	fi
	if [ "`stat -c %U $piddir`" != "$USER" ]; then
		chown $USER $piddir
	fi
	daemon --pidfile ${pidfile} /usr/sbin/contrail-server-manager
	RETVAL=$?
}
stop () {
	echo -n $"Stopping $prog: "
	killproc -p ${pidfile} $prog
	RETVAL=$?
	echo
	if [ $RETVAL -eq 0 ] ; then
		rm -f ${pidfile}
	fi
}

restart () {
        stop
        start
}


# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status -p ${pidfile} $prog
	RETVAL=$?
	;;
  restart)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	RETVAL=2
        ;;
esac

exit $RETVAL
