#
# Copyright (c) 2018 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-
# src directory

import sys
import subprocess
import platform

subdirs = [
           'scons',
           ]

libs = ['boost_system', 'boost_thread', 'log4cplus']
libs.append('pthread')

common = DefaultEnvironment().Clone()

libs.append('tbb_debug')

common.Append(CXXFLAGS = '-Wall -Werror -Wsign-compare')
if subprocess.check_output("g++ --version | grep g++ | awk '{print $3}'",
                           shell=True).rstrip() == "4.8.5":
    common.Append(CCFLAGS = '-Wno-narrowing -Wno-conversion-null')

if platform.system().startswith('Linux'):
   if not platform.linux_distribution()[0].startswith('XenServer'):
      common.Append(CCFLAGS = ['-Wno-unused-local-typedefs'])
common.Append(CCFLAGS = [common['CPPDEFPREFIX'] + 'RAPIDJSON_NAMESPACE=contrail_rapidjson'])

BuildEnv = common.Clone()

if sys.platform.startswith('linux'):
    BuildEnv.Append(CCFLAGS = ['-DLINUX'])

for dir in subdirs:
    BuildEnv.SConscript(dir + '/SConscript',
                         exports='BuildEnv',
                         duplicate=0)
