ERR_SVR_NOT_FOUND = 1
ERR_CLSTR_NOT_FOUND = 2
ERR_IMG_NOT_FOUND = 3


ERR_SVR_EXISTS = 4
ERR_CLSTR_EXISTS = 5
ERR_IMG_EXISTS = 6

ERR_IMG_TYPE_INVALID = 7

ERR_OPR_ERROR = 8
ERR_GENERAL_ERROR = 9

ERR_MATCH_KEY_NOT_PRESENT = 10
ERR_MATCH_VALUE_NOT_PRESENT = 11
ERR_INVALID_MATCH_KEY = 12

ERR_IMG_CATEGORY_ERROR = 13
