#!/usr/bin/python

# vim: tabstop=4 shiftwidth=4 softtabstop=4
"""
   Name : server-manager.py
   Author : Abhay Joshi
   Description : This program is a simple cli interface with
   wrapper code to call individual programs such as create, show
   etc.
"""
import argparse
import pdb
import sys
import smgr_create
import smgr_modify
import smgr_delete
import smgr_show
import smgr_upload_image
import smgr_reimage_server
import smgr_provision_server
import smgr_restart_server

commands_dict = {
    'create' : smgr_create.create_config,
    'modify' : smgr_modify.modify_config,
    'delete' : smgr_delete.delete_config,
    'show'   : smgr_show.show_config,
    'upload_image' : smgr_upload_image.upload_image,
    'reimage' : smgr_reimage_server.reimage_server,
    'provision' : smgr_provision_server.provision_server,
    'restart' : smgr_restart_server.restart_server }

def server_manager(args_str=None):
    if not args_str:
        args_str = sys.argv[1:]

    # Process the arguments
    parser = argparse.ArgumentParser(
        description='''server manager client program''',
        usage= '''server-manager <command> [<args>]

The server manager commands are:
   create         Create new server manager objects
   modify         Modify existing server manager objects
   delete         Delete server manager objects
   show           show server manager objects configuration
   upload_image   Upload images to server manager DB
   reimage        Prepare servers for reimaging with given image
   provision      Provision servers to provide configured roles
   restart        Restart servers so that any reimage or provision
                  commands can take effect.
'''
    )
    parser.add_argument(
        'command',
        help='server manager command to run',
        choices=['create', 'modify', 'delete',
                 'show', 'reimage', 'provision',
                 'restart', 'upload_image'])
    args = parser.parse_args(sys.argv[1:2])
    commands_dict[args.command](sys.argv[2:])
# End of server_manager

if __name__ == "__main__":
    import cgitb
    cgitb.enable(format='text')

    server_manager(sys.argv[1:])
# End if __name__
